base_images:
  os:
    name: ubi
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
images:
- dockerfile_literal: |-
    FROM os
    RUN pip3 install -r requirements.txt
  from: os
  to: python-test-runner
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit
  commands: python3 -m unittest
  container:
    from: python-test-runner
zz_generated_metadata:
  branch: main
  org: openshift
  repo: osd-alert-analysis
