build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.15
images:
- dockerfile_literal: |-
    FROM src
    RUN yum install -y python3 python3-pip
    RUN pip3 install -r requirements.txt
  from: src
  to: python-test-runner
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit
  commands: python3 -m unittest
  container:
    from: python-test-runner
zz_generated_metadata:
  branch: main
  org: openshift
  repo: osd-alert-analysis
